In [1]:
import seaborn as sns
import pandas as pd 

In [2]:
p_df = sns.load_dataset('penguins')

In [3]:
p_df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [64]:
p_df = p_df.dropna() #drop empty

In [65]:
#predict the weight of a penguin 

In [66]:
#we take the flipper as a predictor and as target variable the body mass 

In [67]:
#we have 2 splits to do, the x and y

# x-y split

In [68]:
X = p_df[['flipper_length_mm']]
y = p_df[['body_mass_g']]

In [69]:
#tran-test split

In [70]:
y

body_mass_g
0         3750.0
1         3800.0
2         3250.0
4         3450.0
5         3650.0
..           ...
338       4925.0
340       4850.0
341       5750.0
342       5200.0
343       5400.0

[333 rows x 1 columns]

In [71]:
from sklearn.model_selection import train_test_split

In [72]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.25, random_state = 100)

In [73]:
X_train

flipper_length_mm
60               185.0
126              191.0
71               190.0
294              216.0
200              187.0
..                 ...
59               194.0
85               194.0
332              213.0
288              220.0
13               191.0

[249 rows x 1 columns]

# create new model

In [74]:
from sklearn.linear_model import LinearRegression

In [75]:
lm = LinearRegression()

In [76]:
model = lm.fit(X_train, y_train)

In [77]:
model.coef_

array([[48.46455556]])

In [78]:
model.intercept_

array([-5538.16645549])

In [79]:
import numpy as np

In [80]:
random_penguin = np.array([187]).reshape(-1,1) #we choose one of the penguins from the X_test

In [81]:
model.predict(random_penguin) #predict weight of the pengion 

/home/yv/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[3524.7054333]])

In [82]:
X_test

flipper_length_mm
184              187.0
181              205.0
340              215.0
52               190.0
296              209.0
..                 ...
225              210.0
142              188.0
102              183.0
15               185.0
194              196.0

[84 rows x 1 columns]

In [83]:
#we create the y_pred

In [84]:
y_pred = model.predict(X_test)

In [85]:
y_test.shape

(84, 1)

In [86]:
np.array(y_test) #those are the predictions for the X_test data

array([[3350.],
       [4550.],
       [4850.],
       [3450.],
       [4600.],
       [4050.],
       [3500.],
       [5150.],
       [5850.],
       [6300.],
       [3500.],
       [3800.],
       [3800.],
       [4600.],
       [5400.],
       [4450.],
       [5550.],
       [3550.],
       [4775.],
       [4850.],
       [3350.],
       [5500.],
       [3400.],
       [3200.],
       [3625.],
       [4150.],
       [5700.],
       [5700.],
       [2900.],
       [3300.],
       [3950.],
       [2925.],
       [4300.],
       [3650.],
       [4300.],
       [5550.],
       [3600.],
       [4700.],
       [4400.],
       [3600.],
       [3450.],
       [5500.],
       [3450.],
       [3500.],
       [4150.],
       [5100.],
       [3775.],
       [3300.],
       [4900.],
       [3775.],
       [3300.],
       [5950.],
       [4250.],
       [3825.],
       [4750.],
       [4875.],
       [3575.],
       [4800.],
       [5550.],
       [4050.],
       [4250.],
       [4975.],
       [

In [87]:
real_vs_pred  = pd.DataFrame({'y_test':y_test['body_mass_g'],'y_pred':pd.DataFrame(y_pred)[0]})

In [88]:
real_vs_pred

y_test       y_pred
0       NaN  3524.705433
1    3800.0  4397.067433
2       NaN  4881.712989
3       NaN  3670.099100
4    3450.0  4590.925656
..      ...          ...
322  4975.0          NaN
327  5500.0          NaN
329  5500.0          NaN
333  5500.0          NaN
340  4850.0          NaN

[151 rows x 2 columns]

In [89]:
from sklearn.metrics import mean_squared_error as mse

In [91]:
mse(real_vs_pred['y_test'], real_vs_pred['y_pred'])   #we check the mean squared error 

ValueError: Input contains NaN.

In [ ]:
scaler.fit(X_train)
scaler.trasnform(X_train)
scaler.trasnsform(X_test)

#scaling and standartatizing is done after the split 